### ISSUE TITLE
fatal error occurs if user-agent is null

### ISSUE THREAD

**Issue by Fenex** [darkfriend/dev2fun.imagecompress#10]
```
<pre>[TypeError] 
Dev2fun\ImageCompress\Convert::getBrowserAgentName(): Argument #1 ($userAgent) must be of type string, null given, called in /var/www/www-root/data/www/site.local/bitrix/modules/dev2fun.imagecompress/lib/Convert.php on line 1075 (0)
/var/www/www-root/data/www/site.local/bitrix/modules/dev2fun.imagecompress/lib/Convert.php:1096
#0: Dev2fun\ImageCompress\Convert::getBrowserAgentName(NULL)
	/var/www/www-root/data/www/site.local/bitrix/modules/dev2fun.imagecompress/lib/Convert.php:1075
#1: Dev2fun\ImageCompress\Convert::checkWebpSupport()
	/var/www/www-root/data/www/site.local/bitrix/modules/dev2fun.imagecompress/lib/Convert.php:334
#2: Dev2fun\ImageCompress\Convert-&gt;process(array)
	/var/www/www-root/data/www/site.local/bitrix/modules/dev2fun.imagecompress/lib/Convert.php:646
#3: Dev2fun\ImageCompress\Convert::CompressImageOnConvertEvent(array)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/tools.php:4741
#4: ExecuteModuleEventEx(array, array)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/file.php:1205
#5: CFile::GetFileSRC(array)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/file.php:1051
#6: CFile::GetFromCache(integer, boolean)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/file.php:1069
#7: CFile::GetByID(integer)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/file.php:1237
#8: CFile::GetFileArray(string)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/file.php:2226
#9: CFile::ResizeImageGet(string, array, integer)
	/var/www/www-root/data/www/site.local/local/templates/yousteel_copy/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/result_modifier.php:571
#10: CBitrixComponentTemplate-&gt;{closure}(string)
	/var/www/www-root/data/www/site.local/local/templates/yousteel_copy/components/bitrix/catalog/catalog/bitrix/catalog.element/.default/result_modifier.php:583
#11: include(string)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/component_template.php:947
#12: CBitrixComponentTemplate-&gt;__IncludeMutatorFile(array, array)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/component_template.php:854
#13: CBitrixComponentTemplate-&gt;IncludeTemplate(array)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/component.php:784
#14: CBitrixComponent-&gt;showComponentTemplate()
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/component.php:724
#15: CBitrixComponent-&gt;includeComponentTemplate()
	/var/www/www-root/data/www/site.local/bitrix/modules/iblock/lib/component/base.php:4710
#16: Bitrix\Iblock\Component\Base-&gt;loadData()
	/var/www/www-root/data/www/site.local/bitrix/modules/iblock/lib/component/base.php:4689
#17: Bitrix\Iblock\Component\Base-&gt;initialLoadAction()
	/var/www/www-root/data/www/site.local/bitrix/modules/iblock/lib/component/element.php:284
#18: Bitrix\Iblock\Component\Element-&gt;initialLoadAction()
	
#19: call_user_func(array)
	/var/www/www-root/data/www/site.local/bitrix/modules/iblock/lib/component/base.php:4876
#20: Bitrix\Iblock\Component\Base-&gt;doAction()
	/var/www/www-root/data/www/site.local/bitrix/modules/iblock/lib/component/base.php:4894
#21: Bitrix\Iblock\Component\Base-&gt;executeComponent()
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/component.php:668
#22: CBitrixComponent-&gt;includeComponent(string, array, object, boolean)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/main.php:1195
#23: CAllMain-&gt;IncludeComponent(string, string, array, object)
	/var/www/www-root/data/www/site.local/local/templates/yousteel_copy/components/bitrix/catalog/catalog/element.php:133
#24: include(string)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/component_template.php:790
#25: CBitrixComponentTemplate-&gt;__IncludePHPTemplate(array, array, string)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/component_template.php:885
#26: CBitrixComponentTemplate-&gt;IncludeTemplate(array)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/component.php:784
#27: CBitrixComponent-&gt;showComponentTemplate()
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/component.php:724
#28: CBitrixComponent-&gt;includeComponentTemplate(string)
	/var/www/www-root/data/www/site.local/bitrix/components/bitrix/catalog/component.php:323
#29: include(string)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/component.php:615
#30: CBitrixComponent-&gt;__includeComponent()
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/component.php:692
#31: CBitrixComponent-&gt;includeComponent(string, array, boolean, boolean)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/main.php:1195
#32: CAllMain-&gt;IncludeComponent(string, string, array, boolean)
	/var/www/www-root/data/www/site.local/catalog/index.php:338
#33: include_once(string)
	/var/www/www-root/data/www/site.local/bitrix/modules/main/include/urlrewrite.php:184
#34: include_once(string)
	/var/www/www-root/data/www/site.local/bitrix/urlrewrite.php:2
----------
</pre><br />
<b>Fatal error</b>:  Uncaught TypeError: Dev2fun\ImageCompress\Convert::getBrowserAgentName(): Argument #1 ($userAgent) must be of type string, null given, called in /var/www/www-root/data/www/site.local/bitrix/modules/dev2fun.imagecompress/lib/Convert.php on line 1075 and defined in /var/www/www-root/data/www/site.local/bitrix/modules/dev2fun.imagecompress/lib/Convert.php:1096
Stack trace:
#0 /var/www/www-root/data/www/site.local/bitrix/modules/dev2fun.imagecompress/lib/Convert.php(1075): Dev2fun\ImageCompress\Convert::getBrowserAgentName(NULL)
#1 /var/www/www-root/data/www/site.local/bitrix/modules/dev2fun.imagecompress/lib/Convert.php(876): Dev2fun\ImageCompress\Convert::checkWebpSupport()
#2 /var/www/www-root/data/www/site.local/bitrix/modules/main/tools.php(4741): Dev2fun\ImageCompress\Convert::PostConverterEvent('&lt;!DOCTYPE html&gt;...')
#3 /var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/main.php(3400): ExecuteModuleEventEx(Array, Array)
#4 [internal function]: CAllMain-&gt;EndBufferContent('&lt;!DOCTYPE html&gt;...', 9)
#5 /var/www/www-root/data/www/site.local/bitrix/modules/main/classes/general/main.php(3655): ob_end_flush()
#6 [internal function]: CAllMain::{closure}()
#7 {main}
  thrown in <b>/var/www/www-root/data/www/site.local/bitrix/modules/dev2fun.imagecompress/lib/Convert.php</b> on line <b>1096</b><br />
```

**Comment by darkfriend** [comment]
поправлено в версии 0.8.4
